DESKTOP-LM3GTRG.localdomain
*** Reading local file: /root/airflow/logs/dag_id=weather_data_extract/run_id=scheduled__2022-10-31T05:00:00+00:00/task_id=merge_dataframes/attempt=1.log
[2022-10-31T00:27:46.792-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: weather_data_extract.merge_dataframes scheduled__2022-10-31T05:00:00+00:00 [queued]>
[2022-10-31T00:27:46.825-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: weather_data_extract.merge_dataframes scheduled__2022-10-31T05:00:00+00:00 [queued]>
[2022-10-31T00:27:46.826-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-31T00:27:46.826-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-31T00:27:46.826-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-31T00:27:47.220-0600] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): merge_dataframes> on 2022-10-31 05:00:00+00:00
[2022-10-31T00:27:47.225-0600] {standard_task_runner.py:55} INFO - Started process 4490 to run task
[2022-10-31T00:27:47.240-0600] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_extract', 'merge_dataframes', 'scheduled__2022-10-31T05:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp2xbx9mg1']
[2022-10-31T00:27:47.243-0600] {standard_task_runner.py:83} INFO - Job 7: Subtask merge_dataframes
[2022-10-31T00:27:48.191-0600] {task_command.py:376} INFO - Running <TaskInstance: weather_data_extract.merge_dataframes scheduled__2022-10-31T05:00:00+00:00 [running]> on host DESKTOP-LM3GTRG.localdomain
[2022-10-31T00:27:48.908-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=weather_data_extract
AIRFLOW_CTX_TASK_ID=merge_dataframes
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T05:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T05:00:00+00:00
[2022-10-31T00:27:48.911-0600] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-10-31T00:27:48.917-0600] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /root/project/merge_df.py /root/project/']
[2022-10-31T00:27:48.934-0600] {subprocess.py:86} INFO - Output:
[2022-10-31T00:27:50.303-0600] {subprocess.py:93} INFO - /root/project/current/
[2022-10-31T00:27:50.741-0600] {subprocess.py:97} INFO - Command exited with return code 0
[2022-10-31T00:27:51.356-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=weather_data_extract, task_id=merge_dataframes, execution_date=20221031T050000, start_date=20221031T062746, end_date=20221031T062751
[2022-10-31T00:27:51.650-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-31T00:27:51.676-0600] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

